/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   tutorialSidebar: [
//     {
//       type: 'doc',
//       id: 'introduction', // document ID
//     },
//     {
//       type: 'category',
//       label: 'Ejercicios',
//       items: [
//         {
//           type: 'category',
//           label: '2024-2',
//           items: [
//             {
//               type: 'category',
//               label: 'Ciencias',
//               items: [
//                 {
//                   type: 'category',
//                   label: 'Dinámica',
//                   items: [
//                     {
//                       type: 'autogenerated',
//                       dirName: 'exercises/2024_2/science/dynamics',
//                     },
//                   ],
//                 },
//               ],
//             },
//             {
//               type: 'category',
//               label: 'Matemáticas',
//               items: [
//                 {
//                   type: 'category',
//                   label: 'Probabilidades y Estadística',
//                   items: [
//                     {
//                       type: 'autogenerated',
//                       dirName: 'exercises/2024_2/mathematics/probability_and_statistics',
//                     },
//                   ],
//                 },
//               ],
//             },
//           ],
//         },
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Apuntes',
//       items: [
//         {
//           type: 'category',
//           label: 'Ingeniería',
//           items: [
//             'notes/engineering/computing',
//             'notes/engineering/economics',
//             'notes/engineering/ethics',
//           ],
//         },
//         {
//           type: 'category',
//           label: 'Matemáticas',
//           items: [
//             {
//               type: 'category',
//               label: 'Cálculo 1, 2, 3',
//               items: [
//                 'notes/mathematics/calculus_1_2_3/calculus_1',
//                 'notes/mathematics/calculus_1_2_3/calculus_2',
//                 'notes/mathematics/calculus_1_2_3/calculus_3',
//               ],
//             },
//             'notes/mathematics/differential_equations',
//             'notes/mathematics/linear_algebra',
//             {
//               type: 'category',
//               label: 'Probabilidades y Estadística',
//               items: [
//                 'notes/mathematics/probability_and_statistics/analytics_models',
//                 'notes/mathematics/probability_and_statistics/fundamentals',
//                 'notes/mathematics/probability_and_statistics/inference',
//               ],
//             },
//           ],
//         },
//         {
//           type: 'category',
//           label: 'Ciencias',
//           items: [
//             'notes/science/chemistry',
//             {
//               type: 'category',
//               label: 'Dinámica',
//               items: ['notes/science/dynamics/dinamica_particulas'],
//             },
//             'notes/science/electromagnetism',
//             'notes/science/thermodynamics',
//           ],
//         },
//       ],
//     },
//   ],
// };
};

export default sidebars;
